# Generated by Django 4.0.4 on 2022-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_year_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
