# Generated by Django 4.0.4 on 2022-05-27 18:27

import courses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to=courses.utils.video_directory_path),
        ),
    ]
