# Generated by Django 4.0.5 on 2022-06-25 12:19

import courses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courses.utils.video_directory_path),
        ),
    ]
