# Generated by Django 4.0.5 on 2022-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
