# Generated by Django 4.0.5 on 2022-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AddField(
            model_name='branch',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
