# Generated by Django 4.0.5 on 2022-07-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_lesson_price_branch_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
    ]
