# Generated by Django 4.0.5 on 2022-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_branch_slug_remove_lesson_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
