# Generated by Django 4.0.5 on 2022-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lesson_video_lesson_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
