# Generated by Django 4.1 on 2022-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
