# Generated by Django 4.0.4 on 2022-05-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Year',
            new_name='year',
        ),
    ]
