# Generated by Django 4.0.4 on 2022-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_year_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
