# Generated by Django 4.0.4 on 2022-05-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_registervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervideo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_video', to='student.student'),
        ),
    ]
