# Generated by Django 4.0.5 on 2022-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_otpresetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpresetpassword',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
