# Generated by Django 4.0.5 on 2022-07-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_price'),
        ('student', '0007_alter_otpresetpassword_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervideo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.branch'),
        ),
    ]
